// app-project/dl-angular-app/src/app/shop/shop-side-panel/shop-side-panel.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-shop-side-panel',
  templateUrl: './shop-side-panel.component.html',
  styleUrls: ['./shop-side-panel.component.css']
})
export class ShopSidePanelComponent implements OnInit {

  constructor() { }


  @Input() allProducts: object[]; 
  @Input() currentItem: object;
  ngOnInit(): void {
  }



}

<h4>Other Products</h4>
<ul >
    <li class="side-panel-card" *ngFor="let product of allProducts" [class.select-panel-product]="currentItem.id === product.id">
        <a routerLink='/shop/{{ product.name | linkNameFormated:product.id }}' [queryParams]='{id: product.id}'>
            <img src={{product.image[0]}}>
            <p>{{ product.name }}</p>
            <h4>{{ product.price | currency:'USD'}}</h4>
        </a>
    </li>
</ul>

// app-project/dl-app/src/components/shopComponent/shopSidePanel/shopSidePanel.jsx
import React from "react";
import { NavLink } from "react-router-dom";
import { convertSearchToObject, linkNameCreator } from "../../../business/pageServices";
import "./style.css";


export function ShopSidePanelComponent(props){
    const productId = props.targetId;
    let allProducts = props.allProducts || [];
    let allSideCards = allProducts.map(product => {
        return(
            <li key={product.id} className={ productId == product.id ? "side-panell-inner selected-card" : "side-panell-inner"}>
                <CreateSidePanelCard currentItem={product} productId={productId}></CreateSidePanelCard>
            </li> 
        )
    })
    return(
        <React.Fragment>
            <div className="side-panell-wrapper">
                <h3>Other Product</h3>
                <ul className="side-panel-card-body">
                    {allSideCards ? allSideCards : ""}
                </ul>
            </div>
            
        </React.Fragment>
    )
}

function CreateSidePanelCard(props) {
    const curentProduct = props.currentItem;
    const {
        id,
        name,
        image,
        price
    } = curentProduct;

    let formatedPrice = new Intl.NumberFormat("us-US", {style: 'currency', currency: "USD"}).format(price);
    return(
        <React.Fragment>
            <NavLink to={{
                pathname : linkNameCreator(name) + `?id=${id}`,
                query: {id: id}
            }}>
                <div >
                    <div>
                        <img src={image? image[0] : ""}/>
                    </div>
                    <h4>{name}</h4>
                    <h5>{formatedPrice}</h5>
                </div>
            </NavLink>
            
            
        </React.Fragment>
    )
}
